config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  root 'reports#new'
  resources :reports, only: [:new, :create, :show, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fiscal_document.rb
class FiscalDocument < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :taxes, dependent: :destroy

  validates :serie, :nNF, :dhEmi, :emitente, :destinatario, presence: true

  def total_product_value
    products.sum(:value)
  end

  def total_tax_value
    tax = taxes.first
    tax.icms + tax.ipi + tax.pis + tax.cofins
  end

  def grand_total
    total_product_value + total_tax_value
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :fiscal_document

  validates :name, :ncm, :cfop, :unit, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :value, presence: true, numericality: { greater_than: 0 }
end

app/models/tax.rb
class Tax < ApplicationRecord
  belongs_to :fiscal_document

  validates :icms, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :ipi, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :pis, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cofins, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { user: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reports_controller.rb
require 'base64'

class ReportsController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def index
    return @fiscal_documents = FiscalDocument.all if params.empty?

    filter_service = FiscalDocumentFilterService.new(params)
    @fiscal_documents = filter_service.filter
    @series = filter_service.series
    @nf_numbers = filter_service.nf_numbers
    @emitente_nomes = filter_service.emitente_names
    @destinatario_nomes = filter_service.destinatario_names
    @datas_emissao = filter_service.datas_emissao

    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename=relatorio_fiscal.xlsx'
      }
    end
  end

  def create
    uploaded_file = fetch_uploaded_file

    return handle_missing_file unless uploaded_file_present?(uploaded_file)
    return handle_invalid_file_type unless valid_file_type?(uploaded_file)

    file_path = save_uploaded_file(uploaded_file)

    if uploaded_file.content_type == 'application/zip'
      return handle_invalid_zip_content unless valid_zip_content?(file_path)
    end

    process_file(file_path)
  end

  def show
    @fiscal_document = FiscalDocument.find(params[:id])
    @products = @fiscal_document.products
    @tax = @fiscal_document.taxes.first

    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=relatorio_fiscal_#{params[:id]}.xlsx"
      }
    end
  end

  def destroy
    FiscalDocument.find(params[:id]).destroy

    redirect_to reports_path, notice: 'Documento fiscal deletado.'
  end

  private

  def valid_file_type?(file)
    allowed_types = ['application/xml', 'text/xml', 'application/zip']
    allowed_types.include?(file.content_type)
  end

  def valid_zip_content?(file_path)
    require 'zip'
    valid = true
    Zip::File.open(file_path) do |zip_file|
      zip_file.each do |entry|
        unless entry.name.end_with?('.xml')
          valid = false
          break
        end
      end
    end
    valid
  end

  def fetch_uploaded_file
    params[:report]&.dig(:file)
  end

  def uploaded_file_present?(file)
    file.present?
  end

  def handle_missing_file
    flash.now[:alert] = 'Nenhum arquivo foi enviado. Por favor, selecione um arquivo XML ou ZIP.'
    render :new, status: :unprocessable_entity
  end

  def handle_invalid_file_type
    flash.now[:alert] = 'Tipo de arquivo inválido. Por favor, envie um arquivo XML ou ZIP.'
    render :new, status: :unprocessable_entity
  end

  def save_uploaded_file(file)
    file_path = Rails.root.join('tmp', file.original_filename)
    File.open(file_path, 'wb') do |f|
      f.write(file.read)
    end
    file_path
  end

  def handle_invalid_zip_content
    flash.now[:alert] = 'O arquivo ZIP contém arquivos que não são XML. Por favor, envie um ZIP apenas com arquivos XML.'
    render :new, status: :unprocessable_entity
  end

  def process_file(file_path)
    file_content = File.read(file_path)
    file_extension = File.extname(file_path)

    service = XmlProcessorService.new(file_content, zip_file: file_extension == '.zip')
    extracted_data = service.call

    extracted_data.each do |data|
      XmlProcessorJob.perform_async(data)
    end

    redirect_to new_report_path, notice: 'Seu relatório está sendo gerado...'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_address(address)
    "#{address['rua']}, #{address['numero']} - #{address['bairro']}, #{address['cidade']} - #{address['uf']}"
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioMainoPatrick</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= render "shared/navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/reports/_filters.html.erb
<div class="mx-4 lg:mx-20 my-4 border-b-2 pb-8">
    <%= form_with url: reports_path, method: :get, local: true, class: "space-y-4" do %>
    <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-6">
        <div>
            <%= label_tag :serie, "Número de Série" %>
            <%= select_tag :serie, options_for_select(@series, params[:serie]), include_blank: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500 sm:text-sm" %>
        </div>

        <div>
            <%= label_tag :nNF, "Número da Nota Fiscal" %>
            <%= select_tag :nNF, options_for_select(@nf_numbers, params[:nNF]), include_blank: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500 sm:text-sm" %>
        </div>

        <div>
            <%= label_tag :emitente_nome, "Nome do Emitente" %>
            <%= select_tag :emitente_nome, options_for_select(@emitente_nomes, params[:emitente_nome]), include_blank: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500 sm:text-sm" %>
        </div>

        <div>
            <%= label_tag :destinatario_nome, "Nome do Destinatário" %>
            <%= select_tag :destinatario_nome, options_for_select(@destinatario_nomes, params[:destinatario_nome]), include_blank: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500 sm:text-sm" %>
        </div>

        <div>
            <%= label_tag :dhEmi, "Data de Emissão" %>
            <%= select_tag :dhEmi, options_for_select(@datas_emissao, params[:dhEmi]), include_blank: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500 sm:text-sm" %>
        </div>
        
        <div class="mt-4 flex gap-2 items-end justify-end">
            <%= link_to "Limpar", reports_path, class: "rounded bg-white px-2 py-1 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
            <%= submit_tag "Filtrar", class: "rounded bg-indigo-600 px-2 py-1 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
    </div>
<% end %>
</div>

app/views/reports/_form.html.erb
<div class="flex justify-center items-start min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full bg-white p-8 rounded-lg shadow-lg">
    <h1 class="text-2xl font-bold leading-tight text-gray-900 mb-6">Carregar Documento Fiscal</h1>

    <%= form_with(url: reports_path, local: true, multipart: true, class: "space-y-6") do |form| %>

      <% if flash[:notice] %>
        <div class="p-4 mb-4 text-sm text-green-700 bg-green-100 rounded-lg" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <div>
        <label for="file-upload" class="block text-sm font-medium text-gray-700">Selecione o arquivo XML ou ZIP</label>
        <div class="mt-2 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md">
          <div class="space-y-1 text-center">
            <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
              <path d="M28 8H20v12H8v8h12v12h8V28h12v-8H28V8z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <div class="flex text-sm text-gray-600">
              <label for="file-upload" class="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
                <span>Upload a file</span>
                <input id="file-upload" name="report[file]" type="file" class="sr-only">
              </label>
              <p class="pl-1">ou arraste e solte</p>
            </div>
            <p class="text-xs text-gray-500">
              XML, ZIP até 10MB
            </p>
          </div>
        </div>
      </div>

      <div>
        <%= form.submit "Analisar", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/import.html.erb
<%= render "form" %>

app/views/reports/index.html.erb
<%= render "filters" %>
<div class="flex flex-col mx-4 lg:mx-20 my-10">
  <div class="self-end mb-4">
    <%= link_to 'Exportar para Excel', reports_path(format: :xlsx), class: 'inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500'%>
  </div>
  <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 ">
    <% @fiscal_documents.each do |fiscal_document| %>
      <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
        <div class="flex w-full items-center justify-between space-x-6 p-6">
          <div class="flex-1 truncate">
            <div class="flex items-center justify-between space-x-3">
              <h3 class="truncate text-lg font-medium text-gray-900">
                Relatório #<%= fiscal_document.id %>
              </h3>
              <span class="inline-flex flex-shrink-0 items-center rounded-full bg-blue-50 px-1.5 py-0.5 text-xs font-medium text-blue-700 ring-1 ring-inset ring-blue-600/20">
                <%= fiscal_document.serie %> / <%= fiscal_document.nNF %>
              </span>
            </div>
            <p class="mt-1 truncate text-sm text-gray-500">
              Emitido em: <%= fiscal_document.dhEmi.strftime('%d/%m/%Y %H:%M') %>
            </p>
          </div>
        </div>
        <div>
          <div class="-mt-px flex divide-x divide-gray-200">
            <div class="flex w-0 flex-1 justify-center hover:bg-red-100/50 transition">
              <%= button_to report_path(fiscal_document), method: :delete, data: { turbo_confirm: 'Você tem certeza que deseja excluir esse relatório?' }, class: 'relative inline-flex w-full items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-red-600' do %>
                <span>Excluir</span>
              <% end %>
            </div>
            <div class="flex w-0 flex-1">
              <%= link_to 'Ver Detalhes', report_path(fiscal_document), class: 'relative -mr-px inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-br-lg border border-transparent py-4 text-sm font-semibold text-gray-900 hover:bg-teal-100/50' %>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/reports/new.html.erb
<%= render "form" %>

app/views/reports/show.html.erb
<div class="overflow-hidden bg-white shadow sm:rounded-lg lg:mx-20 my-8 lg:px-10 lg:py-8">
  <div class="px-4 py-6 sm:px-6 flex justify-between items-center">
    <h1 class="text-2xl font-bold leading-7 text-gray-700">Relatório do Documento Fiscal #<%= @fiscal_document.serie %></h1>
    <div class="flex gap-2">
      <%= link_to 'Voltar', reports_path, class: 'inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
      <%= link_to 'Exportar para Excel', report_path(@fiscal_document, format: :xlsx), class: 'inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500'%>
    </div>
  </div>
  <div class="border-t border-gray-100">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Número de Série</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @fiscal_document.serie %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Número da Nota Fiscal</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @fiscal_document.nNF %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Data e Hora de Emissão</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @fiscal_document.dhEmi %></dd>
      </div>
    </dl>
  </div>

  <div class="flex flex-col lg:flex-row lg:gap-10">
    <div class="px-4 py-6 sm:px-6">
      <h3 class="text-lg font-semibold leading-7 text-gray-900">Emitente</h3>
      <div class="border-t border-gray-100 mt-2">
        <dl class="divide-y divide-gray-100">
          <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-900">Nome</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @fiscal_document.emitente['nome'] %></dd>
          </div>
          <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-900">CNPJ</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @fiscal_document.emitente['cnpj'] %></dd>
          </div>
          <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-900">Endereço</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0 max-w-[40ch]"><%= format_address(@fiscal_document.emitente['endereco']) %></dd>
          </div>
        </dl>
      </div>
    </div>

    <div class="px-4 py-6 sm:px-6">
      <h3 class="text-lg font-semibold leading-7 text-gray-900">Destinatário</h3>
      <div class="border-t border-gray-100 mt-2">
        <dl class="divide-y divide-gray-100">
          <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-900">Nome</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @fiscal_document.destinatario['nome'] %></dd>
          </div>
          <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-900">CNPJ</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @fiscal_document.destinatario['cnpj'] %></dd>
          </div>
          <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-900">Endereço</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0 max-w-[40ch]"><%= format_address(@fiscal_document.destinatario['endereco']) %></dd>
          </div>
        </dl>
      </div>
    </div>
  </div>



<div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h2 class="text-xl font-semibold leading-7 text-gray-800">Produtos Listados</h2>
      </div>
    </div>
    <div class="mt-4 flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <table class="min-w-full divide-y divide-gray-300">
            <thead>
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3">Nome</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">NCM</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">CFOP</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Unidade</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Quantidade</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Valor Unitário</th>
              </tr>
            </thead>
            <tbody class="bg-white">
              <% @products.each do |product| %>
              <tr class="even:bg-gray-50">
                <td class="whitespace-normal break-words py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-3 max-w-[40ch]"><%= product.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.ncm %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.cfop %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.unit %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.quantity %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= number_to_currency(@fiscal_document.grand_total, unit: 'R$', separator: ',', delimiter: '.') %></td>
              </tr>
              <% end %>
              <tr class="bg-gray-100 font-semibold text-gray-900">
                <td colspan="4" class="whitespace-nowrap py-4 pl-4 pr-3 text-left text-sm">Total</td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= @products.count %></td>
                <td colspan="2" class="whitespace-nowrap px-3 py-4 text-left text-sm"><%= number_to_currency(@fiscal_document.total_product_value, unit: 'R$', separator: ',', delimiter: '.') %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


<div class="lg:col-start-3 lg:row-end-1 px-4 py-6 sm:px-6 shadow-xl rounded-xl mx-6 mt-4">
<h2 class="text-xl font-semibold leading-7 text-gray-800">Impostos</h2>
  <dl class="mx-auto grid grid-cols-1 gap-px bg-gray-900/5 sm:grid-cols-2 lg:grid-cols-5">
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">ICMS</dt>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= number_to_currency(@tax.icms, unit: 'R$', separator: ',', delimiter: '.') %></dd>
    </div>
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">IPI</dt>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= number_to_currency(@tax.ipi, unit: 'R$', separator: ',', delimiter: '.') %></dd>
    </div>
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">PIS</dt>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= number_to_currency(@tax.pis, unit: 'R$', separator: ',', delimiter: '.') %></dd>
    </div>
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">COFINS</dt>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= number_to_currency(@tax.cofins, unit: 'R$', separator: ',', delimiter: '.') %></dd>
    </div>
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">Total (Produtos + Impostos)</dt>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= number_to_currency(@fiscal_document.grand_total, unit: 'R$', separator: ',', delimiter: '.') %></dd>
    </div>
  </dl>
</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-white shadow-md">
  <div class="mx-10 px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <div class="flex-shrink-0 flex items-center">
        <%= link_to root_path do %>
            <h1 class="text-xl font-base text-gray-700">Desafio Mainô</h1>
        <% end %>
      </div>
      <div class="flex items-center gap-4">
        <% if user_signed_in? %>
            <% if current_page?(reports_path) %>
                <%= link_to 'Importar', root_path, class: "rounded bg-indigo-500 px-2 py-1 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500" %>
            <% elsif FiscalDocument.any? %>
                <%= link_to 'Relatórios', reports_path, class: "rounded bg-indigo-500 px-2 py-1 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500" %>
            <% end %>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "rounded bg-indigo-500 px-2 py-1 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500" %>
        <% else %>
            <%= link_to 'Login', new_user_session_path, class: "rounded bg-indigo-500 px-2 py-1 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>